### PR TITLE
ksreddy20 adding home town Mountain View.md

### PR DESCRIPTION
**Pull request by ksreddy20**
Request to add Los Angeles to the list.

### CODE REVIEW

**Comment by hemamanne** [comment]
How is the weather up in  MTV?

**Comment by ksreddy20** [comment]
@rajivhota24 - how is the weather out there

**Comment by hemamanne** [comment]
@ksreddy20  :+1:  Go ahead

**Comment by ksreddy20** [comment]
Merge succesfull

**Comment by ksreddy20** [comment]
Succesfully Merged ..closing

**Pull request merged**
