### PR TITLE
YOUR_USERNAME adds hometown of YOUR_HOMETOWN

### PR DESCRIPTION
**Pull request by githubteacher**
Hi all! 👋 

I'm proposing adding Orlando to the list of hometowns, but I have some questions:

1. If you haven't been to Orlando before -- what are you looking forward to?
2. If you *have* been to Orlando -- what did you enjoy the most? Or the least?
3. What kind of food does everyone like? I can make restaurant recommendations based on that.
4. Hey @crichID -- what kinds of things does your son like to do?

### CODE REVIEW

**Comment by joconner** [comment]
Our family enjoyed a Disney cruise out of Orlando. Highly recommended, but a bit 💸

**Comment by crichID** [comment]
@githubteacher thank you for asking! My son :heart:s legos and trains. Any recommendations?

**Comment by githubteacher** [comment]
> Our family enjoyed a Disney cruise out of Orlando. Highly recommended, but a bit 💸

@joconner completely agree -- but I enjoy the quality of Disney cruises so I think it's 💸  well spent!

> My son ❤️s legos and trains. Any recommendations?

Absolutely! I'll add that to my next commit! Stay tuned 🎈

**Comment by joconner** [comment]
👍

**Comment by githubteacher** [comment]
@joconner and @crichID thanks for the feedback! I've added that information in commit abaad0a

**Pull request merged**
